version: "3"
networks:
  default:
    name: eil

services:
  postgres:
    image: postgres:14.5
    restart: always
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "example"
      POSTGRES_DB: "eil"
    ports:
      - 5432:5432
    volumes:
      - ${PG_VOLUME_PATH:-./postgres}:/var/lib/postgresql/data
      # copy the sql script to create tables
      - ${KC_DB_INIT_SCRIPT_PATH:-./init-database.sh}:/docker-entrypoint-initdb.d/init-database.sh

  postgres-sso:
    image: postgres:14.5
    restart: always
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "example"
      POSTGRES_DB: "keycloak_db"
    ports:
      - 5435:5432
    volumes:
      - ${PG_SSO_VOLUME_PATH:-./postgres-sso}:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@etenlab.com
      PGADMIN_DEFAULT_PASSWORD: asdfasdf
    ports:
      - 8104:80
    depends_on:
      - postgres