name: PostgreSQL Service Example
on: push

jobs:
  runner-job:
    runs-on: ubuntu-latest
    steps:
      # Downloads a copy of the code in your repository before running CI tests
      - name: Check out repository code
        uses: actions/checkout@v3

      - uses: isbang/compose-action@v1.4.1
        with:
          compose-file: "./docker/docker-compose.yml"
          down-flags: "--volumes"
          services: |
            postgres-sso
            keycloak

      - name: Install dependencies
        run: npm ci

      - name: Connect to PostgreSQL
        # Runs a script that creates a PostgreSQL table, populates
        # the table with data, and then retrieves the data
        run: npm start

        # Environment variables used by the `client.js` script to create
        # a new PostgreSQL table.

      # - name: Test Keycloak service
      #   run: netstat -ln | grep 8080
      # - name: A
      #   run: sudo netstat -tulpn
